server:
  port: ${SERVER_PORT:8086} # Puerto por defecto para desarrollo, Railway usará su propio puerto
  servlet:
    context-path: /stats-service

spring:
  application:
    name: stats-service

  # Configuración de la base de datos
  datasource:
    url: ${DATASOURCE_URL} # ¡SIN valor por defecto para seguridad!
    username: ${DATASOURCE_USER} # ¡SIN valor por defecto para seguridad!
    password: ${DATASOURCE_PASS} # ¡SIN valor por defecto para seguridad!
    driver-class-name: org.postgresql.Driver # Mantener explícito, aunque Spring Boot a menudo lo deduce

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:validate} # 'validate' es ideal para producción, 'update' para desarrollo.
                                      # Aquí lo hacemos configurable por variable de entorno.
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false # Generalmente false en producción para rendimiento y seguridad del log
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true # Útil para depuración si show-sql es true, o para logs
