server:
  port: ${PORT:8080}


  servlet:
    context-path: /stats-service

spring:
  application:
    name: stats-service
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.enable: false
      mail.smtp.ssl.trust: ${MAIL_HOST}
    default-encoding: UTF-8

  datasource:
    url: jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:railway}
    username: ${PGUSER:postgres}
    password: ${PGPASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect 

jwt:
  secret: ${JWT_SECRET}
  accessMs: ${JWT_ACCESS_MS:3600000}
  refreshMs: ${JWT_REFRESH_MS:86400000}

admin:
  email: ${ADMIN_EMAIL}

docker:
  compose:
    enabled: false

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    com.tuaplicacion: DEBUG 

